version: '2'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server

  producer:
    image: 'kafka-producer:1.0'
    volumes:
      - ./data:/etc/data
    command: /etc/data
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    depends_on:
      - kafka-server

  streams:
    image: 'kafka-streams:1.0'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    depends_on:
      - producer

  consumer:
    image: 'kafka-consumer:1.0'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
      - '8090:8090'
    depends_on:
      - streams