version: '3.5'

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - devnetwork

  kafka-server:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
    networks:
      - devnetwork

  producer:
    image: 'kafka-producer:1.0'
    volumes:
      - ./data:/etc/data
    command: /etc/data kafka-server:9092
    depends_on:
      - kafka-server
    networks:
      - devnetwork

  streams:
    image: 'kafka-streams:1.0'
    command: kafka-server:9092
    depends_on:
      - producer
    networks:
      - devnetwork

  consumer:
    image: 'kafka-consumer:1.0'
    ports:
      - '8090:8090'
    command: kafka-server:9092
    depends_on:
      - streams
    networks:
      - devnetwork

networks:
    devnetwork:
      driver: bridge
      name: devnetwork
