version: '2'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server

  producer:
    image: 'kafka-producer:1.0'
    command: dirNameHere
    networks:
      - kafka-net
    #ports:
    #  - '9200:9200'

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    container_name: es
    networks:
      - kafka-net
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    networks:
      - kafka-net
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200